server:
   port: 8003
spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9093
      group-id: consumer-1
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
    producer:
        bootstrap-servers: localhost:9093
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
